name: Update-Timestamp

on:
  push

jobs:
  update-timestamp:
    runs-on: ubuntu-latest

    steps:
      - name: Set Git user
        run: |
          git config --global user.name "GH Actions"
          git config --global user.email "ghActions@github.com"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create or update timestamp in CONFIG.env
        run: |
          # Set the timezone to PST
          export TZ='America/Los_Angeles'
          current_timestamp=$(date +'%Y%m%d%H%M')
          mkdir -p config
          config_file="config/CONFIG.env"
          
          # Check if CONFIG.env exists
          if [ -f "$config_file" ]; then
            # If CONFIG.env exists, update the 'timestamp' key value
            sed -i "s/^timestamp=.*/timestamp=${current_timestamp}/" "$config_file"
          else
            # If CONFIG.env doesn't exist, create it with the 'timestamp' key
            echo "timestamp=${current_timestamp}" > "$config_file"

      - name: Commit CONFIG.env
        run: |
          git add config
          git commit -m "Update timestamp in CONFIG.env" || echo "No changes to commit"
          git push